# Standard rustfmt configuration
edition = "2021"                   # Set to your Rust edition (2015, 2018, or 2021)
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
match_block_trailing_comma = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
